line2d_parameters = {
    # 'xdata': (),
    # 'ydata': (),
    'linewidth': None,
    'linestyle': 'solid',
    'color': None,
    'marker': None,
    'markersize': None,
    'markeredgecolor': None,
    'markeredgewidth': None,
    'markerfacecolor': None,
    'markerfacecoloralt': 'none',
    'fillstyle': 'full',
    'antialiased': True,
    'dash_capstyle': 'butt',
    'dash_joinstyle': 'round',
    'solid_capstyle': 'projecting',
    'solid_joinstyle': 'round',
    'pickradius': 5,
    'drawstyle': 'default',
    'markevery': None,
    'zorder': None,
}

errorbar_parameters = {
    # 'x': None,
    # 'y': None,
    # 'yerr': None,
    # 'xerr': None,
    'fmt': '',
    'color': None,
    'ecolor': None,
    'elinewidth': None,
    'capsize': None,
    'barsabove': False,
    # 'lolims': False,
    # 'uplims': False,
    # 'xlolims': False,
    # 'xuplims': False,
    'errorevery': 1,
    'capthick': None,
    'alpha': None,
    'label': None,
}

plot_parameters = {
    # 'args': (),
    'scalex': True,
    'scaley': True,
    'data': None,
    'label': None,
    'visible': True,
    'color': None,
    # 'linewidth': None,
    # 'linestyle': 'solid',
    # 'marker': None,
    # 'markersize': None,
    # 'markeredgecolor': None,
    # 'markeredgewidth': None,
    # 'markerfacecolor': None,
    # 'markerfacecoloralt': 'none',
    # 'fillstyle': 'full',
    # 'antialiased': True,
    # 'dashes': None,
    # 'drawstyle': 'default',
    # 'solid_capstyle': 'projecting',
    # 'solid_joinstyle': 'round',
    # 'pickradius': 5,
    # 'zorder': 2,
}

scatter_parameters = {
    # 'x': (),
    # 'y': (),
    's': None,
    'c': None,
    'marker': 'o',
    'cmap': None,
    'norm': None,
    'vmin': None,
    'vmax': None,
    'alpha': None,
    'linewidths': None,
    'edgecolors': None,
    'plotnonfinite': False,
    'data': None,
}

collection_parameters = {
    'edgecolors': 'face',
    'facecolors': 'none',
    'linewidths': 1,
    'linestyle': 'solid',
    'antialiaseds': True,
    'transOffset': None,
    'alpha': None,
    'cmap': None,
    'norm': None,
    'vmin': None,
    'vmax': None,
    'picker': None,
    'capstyle': 'butt',
    'joinstyle': 'miter',
    'antialiased': True,
    'urls': None,
    'offsets': (0,0),
    'offset_transform': None,
}



# plot_parameters.update(line2d_parameters)
errorbar_parameters.update(line2d_parameters)
scatter_parameters.update(collection_parameters)